domain_name = "millgroup.club"
ec2-region = "us-east-1"
master_ami_name = "jenkins-slave-attachment8"
slave_ami_name = "jenkins-master-2.107.2"
jenkins_password = "1qaz@WSX"
jenkins_username = "millgroup"